//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KonechnyjjTochno
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Маркетолог.
    /// </summary>
    // *** Start programmer edit section *** (Маркетолог CustomAttributes)

    // *** End programmer edit section *** (Маркетолог CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МаркетологE", new string[0])]
    [View("МаркетологL", new string[0])]
    public class Маркетолог : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.KonechnyjjTochno.Персонал fПерсонал;
        
        // *** Start programmer edit section *** (Маркетолог CustomMembers)

        // *** End programmer edit section *** (Маркетолог CustomMembers)

        
        /// <summary>
        /// Маркетолог.
        /// </summary>
        // *** Start programmer edit section *** (Маркетолог.Персонал CustomAttributes)

        // *** End programmer edit section *** (Маркетолог.Персонал CustomAttributes)
        [PropertyStorage(new string[] {
                "Персонал"})]
        [NotNull()]
        public virtual IIS.KonechnyjjTochno.Персонал Персонал
        {
            get
            {
                // *** Start programmer edit section *** (Маркетолог.Персонал Get start)

                // *** End programmer edit section *** (Маркетолог.Персонал Get start)
                IIS.KonechnyjjTochno.Персонал result = this.fПерсонал;
                // *** Start programmer edit section *** (Маркетолог.Персонал Get end)

                // *** End programmer edit section *** (Маркетолог.Персонал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Маркетолог.Персонал Set start)

                // *** End programmer edit section *** (Маркетолог.Персонал Set start)
                this.fПерсонал = value;
                // *** Start programmer edit section *** (Маркетолог.Персонал Set end)

                // *** End programmer edit section *** (Маркетолог.Персонал Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МаркетологE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МаркетологE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МаркетологE", typeof(IIS.KonechnyjjTochno.Маркетолог));
                }
            }
            
            /// <summary>
            /// "МаркетологL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МаркетологL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МаркетологL", typeof(IIS.KonechnyjjTochno.Маркетолог));
                }
            }
        }
    }
}
