//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KonechnyjjTochno
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спрос.
    /// </summary>
    // *** Start programmer edit section *** (Спрос CustomAttributes)

    // *** End programmer edit section *** (Спрос CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпросE", new string[] {
            "Номер as \'Номер\'",
            "Цена as \'Цена\'",
            "КатегорНомера as \'Категор номера\'",
            "ЗанятВМесяц as \'Занят в месяц\'",
            "Юридич as \'Юридич\'",
            "БроньЧерСайт as \'Бронь чер сайт\'",
            "СкПриДлитПрож as \'Ск при длит прож\'",
            "СкДр as \'Ск др\'",
            "СкВторНомер as \'Ск втор номер\'",
            "СуммСоСкид as \'Сумм со скид\'"})]
    [View("СпросL", new string[] {
            "Номер as \'Номер\'",
            "Цена as \'Цена\'",
            "КатегорНомера as \'Категор номера\'",
            "ЗанятВМесяц as \'Занят в месяц\'",
            "Юридич as \'Юридич\'",
            "БроньЧерСайт as \'Бронь чер сайт\'",
            "СкПриДлитПрож as \'Ск при длит прож\'",
            "СкДр as \'Ск др\'",
            "СкВторНомер as \'Ск втор номер\'",
            "СуммСоСкид as \'Сумм со скид\'"})]
    public class Спрос : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private int fЦена;
        
        private int fКатегорНомера;
        
        private int fЗанятВМесяц;
        
        private bool fЮридич;
        
        private bool fБроньЧерСайт;
        
        private bool fСкПриДлитПрож;
        
        private bool fСкДр;
        
        private bool fСкВторНомер;
        
        private int fСуммСоСкид;
        
        private IIS.KonechnyjjTochno.Маркетолог fМаркетолог;
        
        // *** Start programmer edit section *** (Спрос CustomMembers)

        // *** End programmer edit section *** (Спрос CustomMembers)

        
        /// <summary>
        /// БроньЧерСайт.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.БроньЧерСайт CustomAttributes)

        // *** End programmer edit section *** (Спрос.БроньЧерСайт CustomAttributes)
        public virtual bool БроньЧерСайт
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.БроньЧерСайт Get start)

                // *** End programmer edit section *** (Спрос.БроньЧерСайт Get start)
                bool result = this.fБроньЧерСайт;
                // *** Start programmer edit section *** (Спрос.БроньЧерСайт Get end)

                // *** End programmer edit section *** (Спрос.БроньЧерСайт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.БроньЧерСайт Set start)

                // *** End programmer edit section *** (Спрос.БроньЧерСайт Set start)
                this.fБроньЧерСайт = value;
                // *** Start programmer edit section *** (Спрос.БроньЧерСайт Set end)

                // *** End programmer edit section *** (Спрос.БроньЧерСайт Set end)
            }
        }
        
        /// <summary>
        /// ЗанятВМесяц.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.ЗанятВМесяц CustomAttributes)

        // *** End programmer edit section *** (Спрос.ЗанятВМесяц CustomAttributes)
        public virtual int ЗанятВМесяц
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.ЗанятВМесяц Get start)

                // *** End programmer edit section *** (Спрос.ЗанятВМесяц Get start)
                int result = this.fЗанятВМесяц;
                // *** Start programmer edit section *** (Спрос.ЗанятВМесяц Get end)

                // *** End programmer edit section *** (Спрос.ЗанятВМесяц Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.ЗанятВМесяц Set start)

                // *** End programmer edit section *** (Спрос.ЗанятВМесяц Set start)
                this.fЗанятВМесяц = value;
                // *** Start programmer edit section *** (Спрос.ЗанятВМесяц Set end)

                // *** End programmer edit section *** (Спрос.ЗанятВМесяц Set end)
            }
        }
        
        /// <summary>
        /// КатегорНомера.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.КатегорНомера CustomAttributes)

        // *** End programmer edit section *** (Спрос.КатегорНомера CustomAttributes)
        public virtual int КатегорНомера
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.КатегорНомера Get start)

                // *** End programmer edit section *** (Спрос.КатегорНомера Get start)
                int result = this.fКатегорНомера;
                // *** Start programmer edit section *** (Спрос.КатегорНомера Get end)

                // *** End programmer edit section *** (Спрос.КатегорНомера Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.КатегорНомера Set start)

                // *** End programmer edit section *** (Спрос.КатегорНомера Set start)
                this.fКатегорНомера = value;
                // *** Start programmer edit section *** (Спрос.КатегорНомера Set end)

                // *** End programmer edit section *** (Спрос.КатегорНомера Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.Номер CustomAttributes)

        // *** End programmer edit section *** (Спрос.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.Номер Get start)

                // *** End programmer edit section *** (Спрос.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Спрос.Номер Get end)

                // *** End programmer edit section *** (Спрос.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.Номер Set start)

                // *** End programmer edit section *** (Спрос.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Спрос.Номер Set end)

                // *** End programmer edit section *** (Спрос.Номер Set end)
            }
        }
        
        /// <summary>
        /// СкВторНомер.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.СкВторНомер CustomAttributes)

        // *** End programmer edit section *** (Спрос.СкВторНомер CustomAttributes)
        public virtual bool СкВторНомер
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.СкВторНомер Get start)

                // *** End programmer edit section *** (Спрос.СкВторНомер Get start)
                bool result = this.fСкВторНомер;
                // *** Start programmer edit section *** (Спрос.СкВторНомер Get end)

                // *** End programmer edit section *** (Спрос.СкВторНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.СкВторНомер Set start)

                // *** End programmer edit section *** (Спрос.СкВторНомер Set start)
                this.fСкВторНомер = value;
                // *** Start programmer edit section *** (Спрос.СкВторНомер Set end)

                // *** End programmer edit section *** (Спрос.СкВторНомер Set end)
            }
        }
        
        /// <summary>
        /// СкДр.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.СкДр CustomAttributes)

        // *** End programmer edit section *** (Спрос.СкДр CustomAttributes)
        public virtual bool СкДр
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.СкДр Get start)

                // *** End programmer edit section *** (Спрос.СкДр Get start)
                bool result = this.fСкДр;
                // *** Start programmer edit section *** (Спрос.СкДр Get end)

                // *** End programmer edit section *** (Спрос.СкДр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.СкДр Set start)

                // *** End programmer edit section *** (Спрос.СкДр Set start)
                this.fСкДр = value;
                // *** Start programmer edit section *** (Спрос.СкДр Set end)

                // *** End programmer edit section *** (Спрос.СкДр Set end)
            }
        }
        
        /// <summary>
        /// СкПриДлитПрож.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.СкПриДлитПрож CustomAttributes)

        // *** End programmer edit section *** (Спрос.СкПриДлитПрож CustomAttributes)
        public virtual bool СкПриДлитПрож
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.СкПриДлитПрож Get start)

                // *** End programmer edit section *** (Спрос.СкПриДлитПрож Get start)
                bool result = this.fСкПриДлитПрож;
                // *** Start programmer edit section *** (Спрос.СкПриДлитПрож Get end)

                // *** End programmer edit section *** (Спрос.СкПриДлитПрож Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.СкПриДлитПрож Set start)

                // *** End programmer edit section *** (Спрос.СкПриДлитПрож Set start)
                this.fСкПриДлитПрож = value;
                // *** Start programmer edit section *** (Спрос.СкПриДлитПрож Set end)

                // *** End programmer edit section *** (Спрос.СкПриДлитПрож Set end)
            }
        }
        
        /// <summary>
        /// СуммСоСкид.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.СуммСоСкид CustomAttributes)

        // *** End programmer edit section *** (Спрос.СуммСоСкид CustomAttributes)
        public virtual int СуммСоСкид
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.СуммСоСкид Get start)

                // *** End programmer edit section *** (Спрос.СуммСоСкид Get start)
                int result = this.fСуммСоСкид;
                // *** Start programmer edit section *** (Спрос.СуммСоСкид Get end)

                // *** End programmer edit section *** (Спрос.СуммСоСкид Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.СуммСоСкид Set start)

                // *** End programmer edit section *** (Спрос.СуммСоСкид Set start)
                this.fСуммСоСкид = value;
                // *** Start programmer edit section *** (Спрос.СуммСоСкид Set end)

                // *** End programmer edit section *** (Спрос.СуммСоСкид Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.Цена CustomAttributes)

        // *** End programmer edit section *** (Спрос.Цена CustomAttributes)
        public virtual int Цена
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.Цена Get start)

                // *** End programmer edit section *** (Спрос.Цена Get start)
                int result = this.fЦена;
                // *** Start programmer edit section *** (Спрос.Цена Get end)

                // *** End programmer edit section *** (Спрос.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.Цена Set start)

                // *** End programmer edit section *** (Спрос.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Спрос.Цена Set end)

                // *** End programmer edit section *** (Спрос.Цена Set end)
            }
        }
        
        /// <summary>
        /// Юридич.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.Юридич CustomAttributes)

        // *** End programmer edit section *** (Спрос.Юридич CustomAttributes)
        public virtual bool Юридич
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.Юридич Get start)

                // *** End programmer edit section *** (Спрос.Юридич Get start)
                bool result = this.fЮридич;
                // *** Start programmer edit section *** (Спрос.Юридич Get end)

                // *** End programmer edit section *** (Спрос.Юридич Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.Юридич Set start)

                // *** End programmer edit section *** (Спрос.Юридич Set start)
                this.fЮридич = value;
                // *** Start programmer edit section *** (Спрос.Юридич Set end)

                // *** End programmer edit section *** (Спрос.Юридич Set end)
            }
        }
        
        /// <summary>
        /// Спрос.
        /// </summary>
        // *** Start programmer edit section *** (Спрос.Маркетолог CustomAttributes)

        // *** End programmer edit section *** (Спрос.Маркетолог CustomAttributes)
        [PropertyStorage(new string[] {
                "Маркетолог"})]
        [NotNull()]
        public virtual IIS.KonechnyjjTochno.Маркетолог Маркетолог
        {
            get
            {
                // *** Start programmer edit section *** (Спрос.Маркетолог Get start)

                // *** End programmer edit section *** (Спрос.Маркетолог Get start)
                IIS.KonechnyjjTochno.Маркетолог result = this.fМаркетолог;
                // *** Start programmer edit section *** (Спрос.Маркетолог Get end)

                // *** End programmer edit section *** (Спрос.Маркетолог Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Спрос.Маркетолог Set start)

                // *** End programmer edit section *** (Спрос.Маркетолог Set start)
                this.fМаркетолог = value;
                // *** Start programmer edit section *** (Спрос.Маркетолог Set end)

                // *** End programmer edit section *** (Спрос.Маркетолог Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпросE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпросE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпросE", typeof(IIS.KonechnyjjTochno.Спрос));
                }
            }
            
            /// <summary>
            /// "СпросL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпросL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпросL", typeof(IIS.KonechnyjjTochno.Спрос));
                }
            }
        }
    }
}
